trigger: none # Disable the branch trigger
pr: none # Disable PR trigger

# Choose a package to publish at the time of job creation
parameters:
  - name: packageToPublish
    displayName: Package to Publish
    type: string
    default: microsoft-compose-language-service
  - name: publishVersion
    displayName: Publish Version
    type: string
  - name: dryRun
    displayName: Dry Run
    type: boolean
    default: false

# Grab the base templates from https://github.com/microsoft/vscode-azuretools/tree/main/azure-pipelines
resources:
  repositories:
    - repository: templates
      type: github
      name: microsoft/vscode-azuretools
      ref: main
      endpoint: GitHub-AzureTools
  pipelines:
    - pipeline: build # This must be "build"
      source: \Azure Tools\VSCode\Packages\compose-language-service # name of the pipeline that produces the artifacts

# Use those base templates
extends:
  template: azure-pipelines/1es-release-npm.yml@templates
  parameters:
    packageToPublish: ${{ parameters.packageToPublish }}
    publishVersion: ${{ parameters.publishVersion }}
    dryRun: ${{ parameters.dryRun }}
    OwnerAlias: "devinb"
    ApproverAlias: "bwater"
