trigger: none # Disable the branch trigger
pr: none # Disable PR trigger

# Choose a package to publish at the time of job creation
parameters:
  - name: PackageToPublish
    displayName: Package to Publish
    type: string
    default: microsoft-compose-language-service
  - name: BranchToPublish
    displayName: Branch to Publish
    type: string
    default: "refs/heads/main"

# Grab the base templates from https://github.com/microsoft/vscode-azuretools/tree/main/azure-pipelines
resources:
  repositories:
    - repository: templates
      type: github
      name: microsoft/vscode-azuretools
      ref: main
      endpoint: GitHub-AzureTools

# Use those base templates
extends:
  template: azure-pipelines/1es-release-npm.yml@templates
  parameters:
    PackageToPublish: ${{ parameters.PackageToPublish }}
    BranchToPublish: ${{ parameters.BranchToPublish }}
    PipelineDefinition: 20290
    OwnerAlias: "devinb"
    ApproverAlias: "bwater"
